CREATE ROLE "buyer" NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE "manager" NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE "general_manager" NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

GRANT SELECT ON TABLE alcohol, brand, factory, region TO GROUP "buyer", "manager", "general_manager";
GRANT UPDATE ON TABLE alcohol TO GROUP "manager", "general_manager";
GRANT DELETE ON TABLE alcohol TO GROUP "general_manager";
GRANT INSERT ON TABLE brand, factory, region TO GROUP "general_manager";